### ISSUE TITLE
New version of SLICOT in the near future

### ISSUE THREAD

**Issue by andreasvarga** [RalphAS/SLICOTMath.jl#2]
A new version of SLICOT is under preparation, as communicated by Vasile Sima. I am already scared what troubles (or not?) may this bring.
Good news are that apparently SLICOT has been also tested under MKL (but who knows what surprises can pop up). My recent experience (see [here](https://github.com/SciML/LinearSolve.jl/issues/427)) was not a pleasant one.

**Comment by andreasvarga** [comment]
Version v5.9 of SLICOT has been finally released. I wonder if you could help once again to generate the corresponding libraries. Many thanks in advance.

**Comment by RalphAS** [comment]
An attempt at the library JLL is in the queue:
https://github.com/JuliaPackaging/Yggdrasil/pull/8227

Are you still using your own `ccall` wrappers?  I won't have time to update this package for a while.

**Comment by andreasvarga** [comment]
Great! Yes, I am using my own wrappers which use directly SLICOT_jll. 

> I won't have time to update this package for a while.

Which package you mean?

**Comment by andreasvarga** [comment]
Thanks.
